Fix tab (change to spaces)
Fixes:

$ python ExplorerTest.py
  File "ExplorerTest.py", line 6
    time.sleep(3)
    ^
IndentationError: unexpected indent